Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	phyluce_run1
	2

[Wed Mar 23 13:39:10 2022]
rule phyluce_run1:
    input: /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.fasta, /home/arthur/Bureau/postdocs/isem/hybscan/pipeline/tools/uce-probes.fasta
    output: /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce.fasta, /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce
    jobid: 1
    wildcards: PATH=/home/arthur/Bureau/postdocs/isem/hybscan/data, ID=SRR5437981, EXT=.fastp.megahit.

[Wed Mar 23 13:39:11 2022]
Error in rule phyluce_run1:
    jobid: 1
    output: /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce.fasta, /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce

RuleException:
CalledProcessError in line 128 of /home/arthur/Bureau/postdocs/isem/hybscan/pipeline/Snakefile:
Command ' set -euo pipefail;  set +eu;. $(conda info --base)/etc/profile.d/conda.sh;conda activate phyluce_env;mkdir /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce/input;phyluce_assembly_match_contigs_to_probes --contigs /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce/input --probes /home/arthur/Bureau/postdocs/isem/hybscan/pipeline/tools/uce-probes.fasta --output /home/arthur/Bureau/postdocs/isem/hybscan/data/SRR5437981.fastp.megahit.phyluce/output; ' returned non-zero exit status 2.
  File "/home/arthur/Bureau/postdocs/isem/hybscan/pipeline/Snakefile", line 128, in __rule_phyluce_run1
  File "/home/arthur/bin/miniconda/envs/hybscan_env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/arthur/Bureau/postdocs/isem/hybscan/pipeline/.snakemake/log/2022-03-23T133910.645834.snakemake.log
